logging:
  level:
    "[org.springframework.vault]": debug
    "[org.springframework.cloud.vault]": debug

spring:
  application:
    name: mongo-es-demo
  config:
    import: vault://
  cloud:
    vault:
      uri: ${spring.cloud.vault.uri}
      token: ${spring.cloud.vault.token}
      scheme: http
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}
  mongodb:
    uri: ${spring.mongodb.uri}
  ssl:
    bundle:
      pem:
        elastic-client:
          truststore:
            certificate: base64:${http_ca_crt_base64}

# Elasticsearch RestClient configuration
elasticsearch:
  base-url:
  username: elastic
  password:
