spring:
  mongodb:
    uri: ${SPRING_MONGODB_URI}

notion:
  api:
    url: https://api.notion.com/v1/databases/
    token: ${NOTION_API_TOKEN:}
    database-id: ${NOTION_API_DATABASE_ID}
    saving-database-id: ${NOTION_API_SAVING_DATABASE_ID}
    version: "2022-06-28"

management:
  endpoints:
    web:
      exposure:
        include: "health,beans,ratelimiters,retries,ratelimiterevents,retryevents,metrics"

resilience4j:
  ratelimiter:
    instances:
      notionRateLimiter:
        subscribeForEvents: true
        eventConsumerBufferSize: 100
