spring:
  mongodb:
    uri: ${mongo_uri}

notion:
  api:
    url: https://api.notion.com/v1/databases/
    token: ${notion_api_token}
    database-id: ${notion_api_database_id}
    saving-database-id: ${notion_api_saving_database_id}
    version: "2022-06-28"

management:
  endpoints:
    web:
      exposure:
        include: "*"
