spring:
  mongodb:
    uri: ${mongo.uri}

notion:
  api:
    url: https://api.notion.com/v1/databases/
    token: ${notion.api.token}
    database-id: ${notion.api.database-id}
    version: "2022-06-28"
