package com.example.controller;

import java.util.Base64;
import java.util.Map;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

@RestController
@RequestMapping("/api/me")
public class EntraIdController {

  private final ObjectMapper objectMapper;

  public EntraIdController(ObjectMapper objectMapper) {
    this.objectMapper = objectMapper;
  }

  /**
   * Endpoint 1: The Enriched Claims Reads the specific headers injected by Apache's
   * OIDCPassClaimsAs directive. Fastest method, requires no token decoding in Java.
   */
  @GetMapping("/claims")
  public ResponseEntity<Map<String, String>> getEnrichedClaims(
      @RequestHeader(value = "OIDC_CLAIM_preferred_username", defaultValue = "Not Provided")
          String username,
      @RequestHeader(value = "OIDC_CLAIM_name", defaultValue = "Not Provided") String name,
      @RequestHeader(value = "OIDC_CLAIM_email", defaultValue = "Not Provided") String email) {

    Map<String, String> userProfile =
        Map.of(
            "username", username,
            "name", name,
            "email", email);

    return ResponseEntity.ok(userProfile);
  }

  /**
   * Endpoint 2: The Raw JWT Token Fetches the exact Base64-encoded string generated by Microsoft
   * Entra ID. Useful if you need to pass the token downstream to another microservice or API.
   */
  @GetMapping("/token/raw")
  public ResponseEntity<String> getRawToken(
      @RequestHeader(value = "OIDC_id_token", required = false) String idToken) {

    if (idToken == null || idToken.isEmpty()) {
      return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body("Missing OIDC_id_token header");
    }

    return ResponseEntity.ok(idToken);
  }

  /**
   * Endpoint 3: The Decoded Payload Rips open the raw JWT token and parses the JSON body into a
   * Map. Useful if you need advanced claims (like roles or groups) that you didn't specify in the
   * Apache OIDCScope.
   */
  @GetMapping("/token/decoded")
  public ResponseEntity<Map<String, Object>> getDecodedTokenPayload(
      @RequestHeader(value = "OIDC_id_token", required = false) String idToken) {

    if (idToken == null || idToken.isEmpty()) {
      return ResponseEntity.status(HttpStatus.UNAUTHORIZED).build();
    }

    try {
      // A JWT string is separated by periods: header.payload.signature
      String[] chunks = idToken.split("\\.");
      if (chunks.length < 2) {
        return ResponseEntity.badRequest().build();
      }

      // Decode the payload (the middle chunk)
      String decodedPayload = new String(Base64.getUrlDecoder().decode(chunks[1]));

      // Parse the JSON string directly into a Java Map
      Map<String, Object> fullClaims =
          objectMapper.readValue(decodedPayload, new TypeReference<Map<String, Object>>() {});

      return ResponseEntity.ok(fullClaims);

    } catch (Exception e) {
      // Log the exception in a real application
      return ResponseEntity.internalServerError().build();
    }
  }
}
