---
name: "Build, Test, and Publish"

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

permissions: {}

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/template-build-test-publish.yml
    with:
      module: "mongo-es-demo"
    permissions:
      security-events: write # Required to upload SARIF reports
      pull-requests: write # Required to post comments on PRs
