---
name: "Build, Test, and Publish"

on:
  push:
    branches:
      - main
      - features/refactor-pipeline # Temporary for testing
    tags:
      - "v*"
  pull_request:

permissions: {}

jobs:
  call-shared-workflow:
    uses: ./.github/workflows/template-build-test-publish.yml
    with:
      module: "notion-mongo-demo"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      security-events: write # Required to upload SARIF reports
      pull-requests: write # Required to post comments on PRs
